services:

  back:
    build: ./src/api/
    ports: 
      - "8000:8000"
    volumes:
      - type: bind
        source: ./data
        target: /app/scripts/

  front:
    build: ./src/client
    ports: 
      - "80:80"
